services:
  api:
    image: steamgameupdates
    ports:
      - "8080:8080"
    networks:
      - back-tier
    depends_on:
      backend:
        condition: service_healthy

  backend:
    image: steamwebpipes
    ports:
      - "8181:8181"
    # volumes:
    # - db-data:/etc/data
    networks:
      - back-tier
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8181" ]
      interval: 30s
      timeout: 10s
      retries: 5

# volumes:
#   db-data:
#     driver: flocker
#     driver_opts:
#       size: "10GiB"

# configs:
#   httpd-config:
#     external: true

# secrets:
#   server-certificate:
#     external: true

networks:
  # The presence of these objects is sufficient to define them
  # front-tier: {}
  back-tier: {}
